### ISSUE TITLE
Add support for Europe West Region

### ISSUE THREAD

**Issue by edoreld** [Lost-Ark-Market-Online/LostArk-Market-Web#1]
I'd like to become a Watcher for the Europe West region. However, when I try to apply, none of the region choices are for Europe West. 

Can you please add support for Europe West?

**Comment by gogodr** [comment]
My bad, I completely missed it. 
I just added support for Europe West both on the Web and on the Watcher app. 
[Fixed on this commit](https://github.com/gogodr/LostArk-Market-Web/commit/042acfe9aec8da162af7471d43187ee450cf1214)
