### ISSUE TITLE
[Improvement] Scrape and show helper text.

### ISSUE THREAD

**Issue by ItsCEED** [Lost-Ark-Market-Online/LostArk-Market-Web#10]
Many items are bundled, and I'm sure you are aware of that.

Example: 
![image](https://user-images.githubusercontent.com/20998381/166167054-e1f8fdee-346b-4496-b0fd-720057cda993.png)

Not sure if the issue should be here, but most of this can be hard codded in the database or in a separate file as it won't change anytime soon.

It will nice addition in to visuals and overall user experience, plus can be used as data down the road in calculator or other things.

**Comment by gogodr** [comment]
Yes, I was about to tackle this one. I do have the amount information already stored on the information documents for each item ✌

**Comment by gogodr** [comment]
Implemented and deployed along with untradable upon purchase for engraving recipes ✌
