### ISSUE TITLE
[UI] Small color change & possible button change?

### ISSUE THREAD

**Issue by ItsCEED** [Lost-Ark-Market-Online/LostArk-Market-Web#12]
I have an issue creating pull requests and I don't know why.

Anyway change #ab9c77 to #c1a979 across the whole project.
More visible, brighter, and overall better looking.

And since you are it, you can pull the arrows on the sidebar to the right of the button and change the color to #c1a979

Or if you want to be extra:
background: rgb(223,201,148);
background: linear-gradient(180deg, rgba(223,201,148,1) 0%, rgba(204,179,138,1) 100%);

**Comment by gogodr** [comment]
The pull request was there, I even downloaded it. But I saw that you closed it just a couple of seconds after I downloaded it. 
I like the new color which is a little brighter and easier to read, but I would like to tackle in refactoring of the colors alongside this change to make it worthwhile. ( putting all the colors on variables )

**Comment by gogodr** [comment]
Implemented.
