### ISSUE TITLE
[UI] Responsive Layout & Collapsible Side Bar

### ISSUE THREAD

**Issue by tyindeepit** [Lost-Ark-Market-Online/LostArk-Market-Web#13]
The web doesn't scale **down** to the window size. I usually have something static to read/refer to on one half and work on the other half in another application. Would be nice if at least it scale down to better fit smaller/tighter window size. Which leads to the sidebar. Collapsible sidebar would definitely help with this.

This will be good improvement.

**Comment by gogodr** [comment]
The sidebar is collapsible and in a mobile width the only horizontal scrolling enabled is the table. 
Maybe I should make it collapse earlier at a tablet width ?

**Comment by tyindeepit** [comment]
On further investigation, the UI scales, but only to a certain point. Definitely stops scaling before 1280px which is half width of my 2K screen. Would be great if the sidebar collapses earlier or have a toggle or resizable.

**Comment by gogodr** [comment]
I will look into it. I will have it fixed by tomorrow. Thanks for pointing it out. 
I will give it a rest for today tho, Its time to actually play the game for me ✌

**Comment by tyindeepit** [comment]
Sure! Have fun playing!

**Comment by Actlan2** [comment]
Display is very wide and doesn't scale on my screen; sidebar only collapses when at mobile-level screen width.  Suggest optionally-collapsible sidebar and narrower columns to fit all data on half a widescreen width, say at least within 1280 pixels and preferably less. I (and I presume most PC users) will have multiple windows open simultaneously and still need to see all columns.

**Comment by gogodr** [comment]
New UX changes were implemented in the last update. Let me know if you guys feel it better.
The collapsible drawer is now available for desktop and only forced on very large displays. Also gave the mobile version a more app like look with bottom navigation
