### ISSUE TITLE
Discord Link is Expired/Invalid

### ISSUE THREAD

**Issue by danmarzola** [Lost-Ark-Market-Online/LostArk-Market-Web#17]
Hotlink to Discord Invite is expired or invalid

![image](https://user-images.githubusercontent.com/20021542/171869022-b3dd3193-935c-4660-9bd9-b2d5840ac0e6.png)

**Comment by gogodr** [comment]
Sorry I forgot to update the issue. Thanks for the heads up. I updated it. ✌
