### ISSUE TITLE
Website showing double of each entry on NA West/East

### ISSUE THREAD

**Issue by derekszen** [Lost-Ark-Market-Online/LostArk-Market-Web#2]
For example, on my Firefox browser, the website is this on combat supplies:

![image](https://user-images.githubusercontent.com/9856478/165678736-839d8924-f0f0-4df1-915b-ea32f0ae0b30.png)

**Comment by gogodr** [comment]
Thanks for the heads up, there was a problem with the latest update it seems. I am working on fixing it right now.

**Comment by gogodr** [comment]
This problem has been solved. Thanks!
