### ISSUE TITLE
Incorrect images for rare and epic engravings + Master's Tenacity

### ISSUE THREAD

**Issue by EmileMuller** [Lost-Ark-Market-Online/LostArk-Market-Web#20]
Hi! The icons for rare and epic engraving recipe is wrong. The icon for rare engraving recipe the same as uncommon books, and the icon for epic books is the purple one.

![Lost Ark engraving icons](https://user-images.githubusercontent.com/23077995/189536590-27c346b6-81d4-4c4e-b8f3-4e49b61dbc0d.png)

Another issue: Master's Tenacity Engraving Recipe doesn't appear in Lost Ark Market (neither in the list of engraving nor does it show results after searching for it). I'm guessing it's probably because of the apostrophe in the engraving's name.

![Master's Tenacity engr](https://user-images.githubusercontent.com/23077995/189536659-2931236e-1648-4541-8916-3452ec0028ca.png)

Thanks for making Lost Ark Market, amazing tool <3

**Comment by gogodr** [comment]
Thanks for the heads up. 
- The icons problem has been solved (it was a very easy fix)
- Master's Tenacity Engraving Recipes are now enabled and searchable (There was a typo bug in the item information generation procedure)
- The autocomplete item is still not working properly. Once I finish that I will mark this issue as solved.
