### ISSUE TITLE
A few things to update

### ISSUE THREAD

**Issue by EmileMuller** [Lost-Ark-Market-Online/LostArk-Market-Web#21]
Hi there!

I noticed a few things with some items on Lost Ark Market:

The search/autocomplete for "Crystallized Guardian Stone" and "Crystallized Destruction Stone" is using the old name:
* Guardian Stone Crystal -> Crystallized Guardian Stone
* Destruction Stone Crystal -> Crystallized Destruction Stone

For engravings:
* "MP Efficiency Increase" appears before "Magick Stream" while sorting engraving alphabetically. Probably because the sorting algorithm is not using lowercase names.
* Incorrect name: Grace of the Empress -> Empress's Grace
* Incorrect name: Berserker Technique -> Berserker's Technique

As always, thanks for your work on this!

**Comment by gogodr** [comment]
Thanks, sorry for the late reply.
I will look into the autocomplete issue, as for the engravings. In the market tab, the names are correct (Grace of the Empress and Berserker Technique)

**Comment by gogodr** [comment]
Forgot to close the issue, it was fixed and a process for name migrations was implemented. Thanks ✌
