### ISSUE TITLE
API Average price returns wrong number.

### ISSUE THREAD

**Issue by TriXXeD** [Lost-Ark-Market-Online/LostArk-Market-Web#22]
The following items have encountered as returning the wrong value for avgValue, it seems that the decimal is being removed in the response for some reason.

Request:
"https://www.lostarkmarket.online/api/export-market-live/Europe%20Central?items=crystallized-guardian-stone-0&format=csv"

The response returns avgPrice as 24, when it should be 2.4, lowest and recent are correctly returned.
Same issue found with
splendid-protective-potion-2
protective-potion-2
caldarr-thick-raw-meat-2

**Comment by TriXXeD** [comment]
Now also observed occuring for:
stimulant-3 (returning 445 instead of 44.5)
flame-grenade-2 (246 instead of 24.6)
sacred-bomb-2 (245 instead of 24.5)

Crystallized has moved to avg price 2.3, and self corrected. It to be price specific, item may not have any relevance.

**Comment by gogodr** [comment]
My bad for not addressing it in the issues. Most of the updates I announce through the discord. 
There was a little rework on the price scanning strategy and errors like this while they could still happen, have been mitigated.
