### ISSUE TITLE
Some item colors and names

### ISSUE THREAD

**Issue by EmileMuller** [Lost-Ark-Market-Online/LostArk-Market-Web#28]
Hey there!

Found a few things that could be updated regarding item in the market and crafting calculator.

![LostArk Market issues](https://user-images.githubusercontent.com/23077995/211359379-d429a987-b3e6-40c5-b23a-1c779d51151e.png)

- Superior Oreha Fusion Material: orange -> purple rarity
- Obliteration Stone: green -> white rarity
- Protection Stone: green -> white rarity
- Guardian Stone Crystal -> Crystallized Guardian Stone (this was changed on June 30th 2022 Wrath of the Covetous Legion update); also for this one I think the icon isn't loading correctly
- Marvelous Honor Leapstone: purple -> blue rarity

**Comment by gogodr** [comment]
Thanks for the heads up, will fix them either during the week or on this weekend. ✌
