### ISSUE TITLE
Add processing status in the Watcher

### ISSUE THREAD

**Issue by tyindeepit** [Lost-Ark-Market-Online/LostArk-Market-Web#4]
Suggest to add log console or status report about the screenshot processing in Watcher application. Sound cue alone is too annoying when you're doing 50+ screenshots at a time. And it could be used to track/find point of error when it happens.

**Comment by gogodr** [comment]
I will, On the next update I am going to add a log window that you will be able to open from the system tray menu and see all the operations. 
For the time being, if you want to you can disable the sounds in the config menu and just shoot, the more information fed to the platform the better even if some fail. All operations are timestamped so taking screenshots too far apart or too close one to another is not really an issue. ✌

**Comment by tyindeepit** [comment]
Nice to hear this. Will look forward to the log window.

**Comment by gogodr** [comment]
![image](https://user-images.githubusercontent.com/2740936/166060851-717cf9d6-2757-472d-a3ca-dfbab898c622.png)
Its going to look like this, I will be pushing the update in the next couple of hours.

**Comment by gogodr** [comment]
Added into the watcher project version 0.4.4 and is now live to be downloaded through the launcher ✌
