### ISSUE TITLE
[Improvement] Remember Region selection.

### ISSUE THREAD

**Issue by ItsCEED** [Lost-Ark-Market-Online/LostArk-Market-Web#6]
Atm is a bit annoying to switch regions every time you reopen the website.
Make it so it remembers the selection, cookies will do I guess?

**Comment by gogodr** [comment]
Can do, I am already using localstorage to store the favorites. can put in the region in there too so that when you go to the root page it can redirect you to your own region. this should be an easy thing to implement. thanks for the suggestion ✌

**Comment by gogodr** [comment]
This was such an easy thing to implement and so impactful for the user experience. Thank you. ✌
Its already live and running.
