### ISSUE TITLE
[UI] Search bar

### ISSUE THREAD

**Issue by ItsCEED** [Lost-Ark-Market-Online/LostArk-Market-Web#8]
Move the search bar to the left, or make it fluid.

![image](https://user-images.githubusercontent.com/20998381/166163538-d6b67677-aab2-4683-8c89-f48467ceece8.png)

It doesn't look bad either way but on big screen its far fetch to go on the right side just to look up something (at first i haven't even noticed that there is a search bar.)

**Comment by gogodr** [comment]
In the game the search is on the right side, I think I will keep it there because one of the things I also have in backlog it contextual filters like: tier / rarity / class and those would be dropdowns to the left of the search bar.

**Comment by ItsCEED** [comment]
That's correct, I've guessed that you are trying to replicate the market feeling as much as you can.
But the window in-game is much smaller and it sits in eye angle with no issue at all, while here you gotta run and look for the search.

A possible future thing is to implement hotkeys for example CTRL-F to trigger the search bar, including category selection and so on

**Comment by gogodr** [comment]
I will try some experiments to improve the ux on ultra wide monitors. The table really has no reason to have that much blank space with that width. Maybe I should give it a maximum width and just put some illustrations on the sides to fill the blank space. 

I can look into making keyboard shortcuts. I will put this in the backlog. thanks ✌
