### ISSUE TITLE
[UI Improvement] Historical Data hover 5 days history data.

### ISSUE THREAD

**Issue by ItsCEED** [Lost-Ark-Market-Online/LostArk-Market-Web#9]
On hover, show the price of the last 5 days, something like it is in game.

Sorry for bombarding you with Issues, but I'm more than sure most of my requests are fairly simple once considering you already have all the data and mostly they are UI improvements and quick access to some thing that otherwise are not there

**Comment by gogodr** [comment]
I have in backlog showing a minigraph of the last 5~ days embedded in the main table. Like what they have in https://poe.ninja/challenge/currency
( It was suggested in reddit )

For this I have to update the data processing algorith but it is completely doable and something I want to tackle probably this week.

About the issues, please do keep them coming. All suggestions are fully welcome. ✌

**Comment by gogodr** [comment]
Implemented
